version: "3.8"

services:
  backend:
    build: ./backend
    container_name: p2p_backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: p2p_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000

